apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kawaii-image-api
  labels:
    app: kawaii-image-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kawaii-image-api
    spec:
      containers:
      - name: kawaii-image-api
        image: asia.gcr.io/gke-project-181000/kawaii-image-api:latest
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
